### ISSUE TITLE
Previews al final del archivo

### ISSUE THREAD

**Issue by josemontecastelo** [moraiiiss/App-Burguer#3]
https://github.com/moraiiiss/App-Burguer/blob/e70157375f43bcd9aea7e124a4168e2f3604dc3c/app/src/main/java/com/moraiiiss/appburguer/app/Screen/PantallaDetallesHamburguesa/DetallesHamburguesa.kt#L32

Para poner un poco de orden es recomendable posicionar los previews al final del archivo.

**Comment by moraiiiss** [comment]
Solucionado.
